/*FAZER UM PROGRAMA PARA PREENCHER UMA MATRIZ 2x2
O USUARIO SO PODERA DIGITAR 4 VALORES VALIDOS(4 VEZES)
OS VALORES VALIDOS SAO NUMEROS PARES. AO FINAL
O PROGRAMA DEVERA EXIBIR A SOMA DOS VALORES*/
#include<stdio.h>
main()
{
	int a,b,c;
	printf("\n\nFAZER EM CASA\n\n");
}
