/*FAZER UM PROGRAMA PARA PREENCHER DUAS MATRIZES 2x2
COM OS MESMOS VALORES, SENDO QUE NA SEGUNDA MATRIZ
OS VALORES PRECISAM ESTAR EM POSIÇOES DIFERENTES
AO FINAL O PROGRAMA DEVERA APONTAR OS INDICES DOS NUMEROS
DA SEGUNDA MATRIZ COM RELAÇAO NA PRIMEIRA MATRIZ*/
#include<stdio.h>
main()
{
	printf("\n\nAINDA TEM QUE FAZER\n\n");
}
